config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end
  root to: "homes#show"
  resources :groups, only: [:index, :new, :create, :show] do
    member do
      post "join" => "group_memberships#create"
      delete "leave" => "group_memberships#destroy"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resource :dashboard, only: [:show]
  resources :tags, only: [:show]
  resources :galleries do
    resources :images do
      resources :comments, only: [:create]
      resource :like, only: [:create, :destroy]
    end
  end
  #get "/galleries" => "galleries#index"
  #get "/galleries/new" => "galleries#new" #presentation
  #get "/galleries/:id" => "galleries#show", as: :gallery
  #post "/galleries" => "galleries#create" #Persistence or saves to the database
  #get "/galleries/:id/edit" => "galleries#edit"
  #patch "/galleries/:id" => "galleries#update"
  #delete "/galleries/:id" => "galleries#destroy"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :image

  default_scope {order(created_at: :asc)}
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :group_memberships
  has_many :users, through: :group_memberships
  has_and_belongs_to_many :images

  validates :name, presence: true
  validates :description, presence: true

end

app/models/group_membership.rb
class GroupMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  has_many :comments
  has_and_belongs_to_many :groups
  has_many :likes
  acts_as_taggable

  validates :name, presence: true
  validates :description, presence: true
  validates :url, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :image
  belongs_to :user

  validates :user_id, uniqueness: { scope: :image_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :galleries
  has_many :group_memberships
  has_many :groups, through: :group_memberships
  has_many :likes
  has_many :liked_images, through: :likes, source: :image

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def member?(group)
    groups.include?(group)
  end

  def join(group)
    groups << group
  end

  def leave(group)
    groups.delete(group)
  end

  def like(image)
    liked_images << image
  end

  def unlike(image)
    liked_images.delete(image)
  end

  def likes?(image)
    liked_images.include?(image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    image = Image.find(params[:image_id])
    image.comments.create(comment_params)
    redirect_to([image.gallery, image])
  end

  private

  def comment_params
    params.
      require(:comment).
      permit(:content).
      merge(user: current_user)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show

  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :require_login
  def index
    @user = current_user
    @galleries = Gallery.all
  end

  def new
    @gallery = Gallery.new
  end

  def create
    params_with_user_id = gallery_params.merge(user_id: current_user.id)
    @gallery = Gallery.create(params_with_user_id)
    redirect_to current_user
  end

  def show
    @gallery =Gallery.find(params[:id])
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    gallery = Gallery.find(params[:id])
    gallery.update(gallery_params)
    redirect_to "/galleries/#{gallery.id}"
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    redirect_to "/galleries"
  end



  private

  def gallery_params
    params.
      require(:gallery).
      permit(:name, :description)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.users << current_user
    group.save
    redirect_to group
  end

  def show
    @group = Group.find(params[:id])
  end

  private

  def group_params
    params.
      require(:group).
      permit(:name, :description)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    @user = User.new
  end

  def require_login
    if !signed_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def show
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.find(params[:id])
    @comment = Comment.new
  end

  def new
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.new
  end 

  def create
    @gallery = find_gallery
    @image = @gallery.images.new(image_params)
 
    if @image.save
      redirect_to @gallery
    else
      render :new
    end
  end

  def edit
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.find(params[:id])
  end

  def update
    @gallery = find_gallery
    @image = find_image_in(@gallery)
    
    if @image.update(image_params)
      redirect_to @gallery
    else
      render :edit
    end
  end

  def destroy
    gallery = find_gallery
    image = find_image_in(gallery)
    image.destroy
    redirect_to gallery
  end

  private

  def find_image_in(gallery)
    gallery.images.find(params[:id])
  end

  def find_gallery
    Gallery.find(params[:gallery_id])
  end

  def image_params
    params.
      require(:image).
      permit(:name, :description, :url, :tag_list, group_ids: [])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    image = Image.find(params[:image_id])
    current_user.like(image)
    redirect_to [image.gallery, image]
  end

  def destroy
    image = Image.find(params[:image_id])
    current_user.unlike(image)
    redirect_to [image.gallery, image]
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #@user = User.new
  end

  def create 
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  #  cookies.signed[:user_id] = user.id
  #  redirect_to galleries_path
  end

  def destroy
    sign_out
    redirect_to galleries_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @images = Image.tagged_with(@tag.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

  def create 
    @user = sign_up(user_params)
    if @user.valid?
      sign_in(@user)
      redirect_to galleries_path
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groupmemberships_helper.rb
module GroupmembershipsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <h4><%= comment.user.email%></h4>
  posted <%= time_ago_in_words(comment.created_at) %> ago
  <p><%= comment.content %></p>


</div>

app/views/galleries/_form.html.erb
<%= form_for(gallery) do |form| %>
  Name: <%= form.text_field :name %> <br />
  Description: <%= form.text_area :description %> <br />

  <%= form.submit %>
<% end %>

app/views/galleries/_gallery.html.erb
<ul>
    <li>
  <%= link_to gallery.name, gallery %>
   </li>

</ul>

app/views/galleries/edit.html.erb
<h3> Edit this gallery </h3>

<%=render "form", gallery: @gallery %>

app/views/galleries/index.html.erb
<%= link_to "New Gallery", "/galleries/new" %>

<% @galleries.each do |gallery| %>
  <div>
    <%= link_to gallery.name, "galleries/#{gallery.id}" %>
  </div>
<% end %>

app/views/galleries/new.html.erb
<h2>New Gallery</h2>

<%= render "form", gallery: @gallery %>

app/views/galleries/show.html.erb
<h1> <%= @gallery.name %> </h1>

<p> <%= @gallery.description %> </p>

<% @gallery.images.each do |image|%>
  <%= render image %>
<% end%> <br />

<%= link_to "Delete", "/galleries/#{@gallery.id}", method: :delete, data: {confirm: "Are you sure?"} %> <br />

<%= link_to "Edit", "/galleries/#{@gallery.id}/edit" %> <br />

<%= link_to "Add Image", new_gallery_image_path(@gallery) %> <br />

<%= link_to "Back", "/users/id" %>

app/views/images/_form.html.erb
<%= render "errors", object: form.object %>

  Name: <%= form.text_field :name %> <br />
  Description: <%= form.text_area :description %> <br />
  Url: <%= form.text_field :url %> <br />

<div>
  <%= form.collection_check_boxes :group_ids, current_user.groups, :id, :name %>
</div>

<div>
  Tags: <%= form.text_area :tag_list %>
</div>

app/views/images/_image.html.erb
  <%= link_to [image.gallery, image] do%>
    <%= image_tag image.url, width: 200 -%>
  <%  end %>

app/views/images/edit.html.erb
<h2>Edit Image</h2>

<%= form_for([@gallery, @image]) do |form| %>
  <%= render form %>
  <%= form.submit "Edit" %>
<%end%>

app/views/images/new.html.erb
<h2> New Image </h2>

<%= form_for([@gallery, @image]) do |form| %>
  <%= render form %>
  <%= form.submit "Add" %>
<%end%>

app/views/images/show.html.erb
<nav>
  <%= @image.name %>
</nav>

<nav>
  <%= @image.description %>
</nav>

<%= image_tag @image.url %>

<nav>
  Tags:
  <%@image.tags.each do |tag| %>
    <%= link_to tag, tag_path(tag.id) %>
  <%end%>
</nav>

<nav>
  <%= link_to "Edit", edit_gallery_image_path %>
</nav>
<nav>
  <%= link_to "Delete", gallery_image_path, method: :delete, data: { confirm: "Are you sure?"}%>

</nav>

<div class="likes">
  <p><%= pluralize(@image.likes.size, "Like") %></p>

  <% if current_user.likes?(@image) %>
    <%= link_to "Unlike", [@image.gallery, @image, :like], method: :delete %>
  <% else %>
    <%= link_to "Like", [@image.gallery, @image, :like], method: :post %> :D
  <% end %>
</div>

<div class="comments">
  <%= render @image.comments %>

  <%= form_for([@gallery, @image, @comment]) do |form| %>
    <%= form.text_area :content %>
      <%= form.submit "Post" %>
  <% end %>
</div>
<%= link_to "Back", galleries_path %>

app/views/users/new.html.erb
<h2> New User </h2>

<%= render "sign_up_form", user: @user %>

app/views/users/show.html.erb
<%= @user.email %>'s Galleries <br />

<hr />
<%= link_to "New Gallery", "/galleries/new" %><br />
<%= link_to "Create Groups", "/groups/new" %>

<%= render @user.galleries %>

<%= link_to "Back", root_path %>